### ISSUE TITLE
Disappearing Neo content

### ISSUE THREAD

**Issue by mjniland1** [ryssbowh/craft-activity#20] opened 2023-09-28 14:44 UTC
I'm currently running a site with Neo 3.9.4. I've noticed that whenever I have the Craft Activity (2.3.14) plugin installed, my child blocks disappear on the second or third entry save.

https://github.com/ryssbowh/craft-activity/assets/56364768/830dd98a-92b2-40de-8c23-f8f84589e5b6

Craft Pro 4.5.6.1

**Comment by ryssbowh** [comment] 2023-09-29 06:43
Hi,
I don't think that would come from this plugin, in fact I'm building another site with Neo fields (without this plugin) and I'm having the same issue.
Could be the same than this : https://github.com/spicywebau/craft-neo/issues/771

**Comment by ttempleton** [comment] 2023-09-29 11:23
Confirming that I can reproduce this, only when the User Activity plugin is enabled. It happens regardless of whether or not Neo's child block UI element is being used (at first I thought its use might be involved), it happens with the [3.x branch](https://github.com/spicywebau/craft-neo/tree/3.x) where https://github.com/spicywebau/craft-neo/issues/771 / https://github.com/spicywebau/craft-neo/issues/777 are (hopefully) fixed, and it seems to specifically happen if you save the entry soon enough after making the content field change that the entry draft hasn't autosaved yet.

Let me know if there's any way I can help, and I'll keep an eye on this issue in case it turns out to be a Neo bug.

**Comment by ryssbowh** [comment] 2023-10-04 10:22
Hi, I found the issue, related to how Neo fields eager load their blocks.
That should be fixed in 2.3.15, can you please confirm it's fixed for you as well ?

**Comment by mjniland1** [comment] 2023-10-13 15:09
Hi, My content no longer disappears on save but when I click on User Activity in the CP I receive the following error. I have `nableLazyLoadingNewBlocks` set to `false`.

2023-10-13 14:59:44 [web.ERROR] [Twig\Error\RuntimeError] Twig\Error\RuntimeError: Key "order" for array with keys "mode, children" does not exist. in /var/www/html/vendor/ryssbowh/craft-activity/src/templates/field-handlers/neo-field.twig:20
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'order', Array, 'any', false, false)
#1 /var/www/html/storage/runtime/compiled_templates/d6/d66d9b6b6662570938aca4f5bb263a9c.php(163): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'order', Array)
#2 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_8d016235b2d5dfcebcab8911621a7a88->macro_neoBlocks(Array, Object(Ryssbowh\Activity\models\ChangedField), 'blocks')
#3 /var/www/html/storage/runtime/compiled_templates/d6/d66d9b6b6662570938aca4f5bb263a9c.php(61): twig_call_macro(Object(__TwigTemplate_8d016235b2d5dfcebcab8911621a7a88), 'macro_neoBlocks', Array, 40, Array, Object(Twig\Source))
#4 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_8d016235b2d5dfcebcab8911621a7a88->doDisplay(Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /var/www/html/storage/runtime/compiled_templates/19/196109446c79e5fdc511f92593313bc8.php(363): Twig\Template->display(Array)
#7 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_10c69da935f684997736b69d7c6183f0->macro_elementField(Object(Ryssbowh\Activity\models\ChangedField))
#8 /var/www/html/storage/runtime/compiled_templates/4e/4ea7cf98a456df43e2384242d7a10480.php(53): twig_call_macro(Object(__TwigTemplate_10c69da935f684997736b69d7c6183f0), 'macro_elementFi...', Array, 6, Array, Object(Twig\Source))
#9 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9e4690b29cb35533fd8a57d70573d52b->doDisplay(Array, Array)
#10 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#12 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#13 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/View.php(474): Twig\Environment->render('activity/descri...', Array)
#15 /var/www/html/vendor/ryssbowh/craft-activity/src/base/logs/ElementLog.php(35): craft\web\View->renderTemplate('activity/descri...', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Component.php(139): Ryssbowh\Activity\base\logs\ElementLog->getDescription()
#17 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(118): yii\base\Component->__get('description')
#18 /var/www/html/storage/runtime/compiled_templates/80/80360c6efcdd08561200bbd79d33b9bb.php(43): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(Ryssbowh\Activity\models\logs\entries\EntrySaved), 'description', Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_76a64a84f4355f1c0729184aabc405db->doDisplay(Array, Array)
#20 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/html/storage/runtime/compiled_templates/94/941815bdf97eba6f4231f17d5caed06a.php(356): Twig\Template->display(Array)
#22 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_0f9c7d37e1c151ce15989af2b7ee1466->block_content(Array, Array)
#23 /var/www/html/storage/runtime/compiled_templates/7a/7a7734c105f97ffca55257b4a35b39d0.php(645): Twig\Template->displayBlock('content', Array, Array)
#24 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_c70a28261079ed1d6c130d48e4752145->block_main(Array, Array)
#25 /var/www/html/storage/runtime/compiled_templates/7a/7a7734c105f97ffca55257b4a35b39d0.php(377): Twig\Template->displayBlock('main', Array, Array)
#26 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_c70a28261079ed1d6c130d48e4752145->block_body(Array, Array)
#27 /var/www/html/storage/runtime/compiled_templates/06/061de83415c763dd1ec05420f9c4f849.php(94): Twig\Template->displayBlock('body', Array, Array)
#28 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_1da521b5d4b69f3c705d73425ad40c3b->doDisplay(Array, Array)
#29 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#30 /var/www/html/storage/runtime/compiled_templates/0f/0feda1800119dd722187ccb1308bc45a.php(56): Twig\Template->display(Array, Array)
#31 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e7fb4ad1e6e53400e0fe4467b9de2e8e->doDisplay(Array, Array)
#32 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#33 /var/www/html/storage/runtime/compiled_templates/7a/7a7734c105f97ffca55257b4a35b39d0.php(180): Twig\Template->display(Array, Array)
#34 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c70a28261079ed1d6c130d48e4752145->doDisplay(Array, Array)
#35 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#36 /var/www/html/storage/runtime/compiled_templates/94/941815bdf97eba6f4231f17d5caed06a.php(56): Twig\Template->display(Array, Array)
#37 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_0f9c7d37e1c151ce15989af2b7ee1466->doDisplay(Array, Array)
#38 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#39 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#40 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#41 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#42 /var/www/html/vendor/craftcms/cms/src/web/View.php(474): Twig\Environment->render('activity/activi...', Array)
#43 /var/www/html/vendor/craftcms/cms/src/web/View.php(527): craft\web\View->renderTemplate('activity/activi...', Array)
#44 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('activity/activi...', Array, 'cp')
#45 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#46 /var/www/html/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#47 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#48 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#49 /var/www/html/web/index.php(16): yii\base\Application->run()
#50 {main} {"memory":43595720,"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Key \"order\" for array with keys \"mode, children\" does not exist. at /var/www/html/vendor/ryssbowh/craft-activity/src/templates/field-handlers/neo-field.twig:20)"}

**Comment by ryssbowh** [comment] 2023-10-13 16:55
@mjniland1 Fixed that in 2.3.16

**Comment by arlingga** [comment] 2023-10-16 04:33
Hi @ryssbowh , I have the same issue for Craft 3, will the fix be available also for Craft 3 plugin?

**Comment by ryssbowh** [comment] 2023-10-17 03:05
@arlingga I've ported this to the Craft 3 version (version 1.3.12)

**Closed** 2023-11-21 07:27 UTC
